# -*- coding: utf-8 -*-
import requests
import pytest
import os,sys

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
@pytest.yield_fixture(scope='session')
def test_getToken():
    Token='eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE2MjM5MTYzMDEsImlhdCI6MTYyMzkxNDUwMSwianRpIjoiOWJhODc0MTkzMjQwNDUxOTg1NjQ5ZTc1NmU3Y2EzMDYiLCJzdWIiOiJiYWlsaW5neXUifQ.Ngl-DWVMLaaSKdr7csQQCJ3ceLRQ4ghdRe7FMGAvZ2QnvfAAHYR6-1HfIXXKTlNqOGa0egAWiatA2xthhJp_Rvm4zQ1fF9feQkN4O1rIqHGKfo_GY_jhVmLsTcCppqp1EqmyGzqtp2d8UxpeWJ5Rrsqzn7zoZ42jeNVGa20wRKgqHu0YHJEG3AY0Ly9TNB0SpljNGDA-2xJ0oWdWQJR7OatoBfxT30IMIQW8rudn8mYavf63M6JYaWmG5vIgyWbTU2hnt3z9eA7U-tj9U-bUfgrx7uRFYQUZpwwtjZnBOTBL_EMrDFmbOz3TPV6l9rpMCPoUPCr7piSE8U1GCXj0Qg'
    return Token
