# -*- coding: utf-8 -*-
import requests
import pytest
import os,sys

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
@pytest.fixture(scope='session')
def test_getToken():
    Token='eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE2MjQyNjkyMTEsImlhdCI6MTYyNDI2NzQxMSwianRpIjoiNWYyMmJmOWRjM2I2NDdlZTk1OWVjZTYyMDEyOWNkMjciLCJzdWIiOiJiYWlsaW5neXUifQ.VS2IbF4UC4TInm04JOp9WvCS1caTa503gs89JrbavKkAVBuoHPWh3Lmx7aY5jbdw_1ztLQlCkF-snX7fOUAURfC_Xxk7z4ffXUMLQrafegTcV9kKWfR5Z6d18DyMuD48RzzRjKhr7tuEmPwcTVBQaiNH-qn8hQLmxsz0-R9-3xOPWgShzG6kE9F1Fso6oGVaWdbt6RN5EXFidonQvAmZ2iNfxzj_TocXJnebKeEfuG6VdatqQRlIsZM4IU5hWlxDJR1KqRGiISvc_mfRHFGRPY74XLv4NRMIIu98DmiOx0OyBAB3myqOYW7XfWmhR0KeupGu4ysQI3BE0l8a4E8iCg'
    return Token
